# Site settings
title: Dominicanos 🇩🇴 
email: canaldominicanosgmail.com
description: Dominicanos hasta la tambora 🇩🇴 
# baseurl: "/fractal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "app.canaldominicanos.online" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: "https://irc.activao.com/?#dominicanos"

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
